import { motion } from 'framer-motion';
import { GlassCard } from '../ui/GlassCard';
import { AnimatedCounter } from '../ui/AnimatedCounter';

// 1. Define the shape of a Stat object clearly
interface StatItem {
  value: number;
  label: string;
  desc: string;
  suffix: string;
  prefix?: string; // The '?' makes it optional, so it won't error if missing
}

export default function Stats() {
  // 2. Apply the type to the array
  const stats: StatItem[] = [
    { 
      value: 98, 
      suffix: '%', 
      label: 'Message Open Rate', 
      desc: 'Via WhatsApp & SMS (compared to just 20% for standard email)' 
    },
    { 
      value: 5, 
      suffix: ' Days', 
      label: 'Guaranteed Setup', 
      desc: 'Maximum time from your initial payment to a fully operational system' 
    },
    { 
      value: 80, 
      suffix: '%', 
      label: 'Of Future Revenue', 
      desc: 'Industry average generated by just 20% of loyal, returning customers' 
    },
  ];

  return (
    <section className="relative z-10 max-w-7xl mx-auto px-6 -mt-12 md:-mt-24 mb-24">
      <motion.div
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-100px" }}
        transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] as const }}
      >
        <GlassCard className="p-8 md:p-12">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-12 divide-y md:divide-y-0 md:divide-x divide-white/10">
            {stats.map((stat, idx) => (
              <div key={idx} className="flex flex-col items-center text-center pt-8 md:pt-0 first:pt-0 px-4">
                <div className="text-4xl md:text-5xl font-bold text-white mb-2">
                  <AnimatedCounter 
                    value={stat.value} 
                    prefix={stat.prefix || ''} // Use empty string if prefix is undefined
                    suffix={stat.suffix} 
                  />
                </div>
                <div className="text-lg font-medium text-[var(--color-gold)] mb-1">
                  {stat.label}
                </div>
                <div className="text-sm text-[#A09880]">
                  {stat.desc}
                </div>
              </div>
            ))}
          </div>
        </GlassCard>
      </motion.div>
    </section>
  );
}